### ISSUE TITLE
Console warning @ jdate element date_time

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#336]
Fabrik form::addElements: Cannot add element "test___jdate_nm" of type "FbDateTime" because: window[e[0]] is not a constructor

**Comment by joomlahenk** [comment]
See #308 also

**Comment by skurvish** [comment]
I have seen that myself. not sure what the cause is. It has not seemed to cause any issues with the form loading or saving. I think we should try adding a second jdate element to the page and see if it happens on that one as well. If it is just the internal date_time field it may not be worth troubleshooting.

**Comment by trob** [comment]
Maybe also related to https://github.com/joomlahenk/fabrik/issues/332

**Comment by skurvish** [comment]
Quite possibly. During the construction phase of the form build F! attaches some special stuff to the various elements. My thinking is that the change to the BS5 markup dropped something that the mootools functions are looking for in the DOM. I am also seeing this on the Calc element. I'm investigating.

**Comment by skurvish** [comment]
This issue has been around since the jdate plugin was created and is a simply copy/paste issue. The jdate plugin is creating the javascript json element date showing it as a date element and not a jdate element. Changing this fixes the issue.

Fixed in PR #361

**Comment by joomlahenk** [comment]
Is still not fixed. Now I get in console:
Fabrik form::addElements: Cannot add element "test___jdate_nm" of type "FbJDateTime" because: JoomlaCalendar is not defined

**Comment by skurvish** [comment]
I am not seeing this. I tried in front end and back end for a new form with jdate. No console warnings. 

When you get this error is calendar.j or calendar-min.js loaded?

Need more info.

**Comment by joomlahenk** [comment]
calendar.js or calendar-min.js is not loaded when form is in a modal (use ajax links = yes)
calendar.js or calendar-min.js is loaded when form is not in a modal (use ajax links = no)

**Comment by joomlahenk** [comment]
Maybe this helps: There are even more differences in loading scripts between a modal and a not modal form.
[scripts_ajax_no.txt](https://github.com/joomlahenk/fabrik/files/9817885/scripts_ajax_no.txt)
[scripts_ajax_yes.txt](https://github.com/joomlahenk/fabrik/files/9817886/scripts_ajax_yes.txt)

**Comment by joomlahenk** [comment]
I also tested J!3 for this. In J!3 we have no modal in the backend, only in the frontend. The calendar is displayed
In J!3 we have a modal, but calendar.js is not loaded. At least not on the page, it maybe loaded when I click the calendar button.
So in fact we should prevent a modal form in the backend (also solving other issues with that) and make calendar display in frontend.
It's hard to find where the loading takes place in the code (modal / not modal / frontend / backend). Much is done in ...\Helpers\Html.php

**Comment by skurvish** [comment]
What setting and where are you setting to open in modal?

**Comment by joomlahenk** [comment]
See issue 332, closing this.
