### ISSUE TITLE
Some fileupload issues

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#337]
Version: testing_pkg_fabrik_4.0alpha1 tested on plain J 4.2.3, PHP 8.1.11

1. when the list links are not Ajaxified, upload works, but the list (after saving) shows in the image column:
Warning: Undefined property: stdClass::$openInBrowser in /usr/www/users/prachta/fabrik/plugins/fabrik_element/fileupload/layouts/fabrik-element-fileupload-downloadlink.php on line 10
This disappears when downloads are disabled.

2. in the form, 'Delete' is not displayed as a button, just text, and is also displayed when there is nothing to delete

3. when list links are Ajaxified, upload does only work when "Use Ajax uploads" in the element is enabled as well. The above downloads warning is also shown when downloads are enabled.

4. no text string (EN) for PLG_ELEMENT_FILEUPLOAD_CONFIRM_HARD_DELETE and PLG_ELEMENT_FILEUPLOAD_PREVIEW

**Comment by trob** [comment]
> 3. when list links are Ajaxified, upload does only work when "Use Ajax uploads" in the element is enabled as well.

This is the same as in F3 (AFAIK it's "a HTML thing")

1. should be fixed https://github.com/joomlahenk/fabrik/pull/426

**Comment by trob** [comment]
4. is solved by this commit https://github.com/joomlahenk/fabrik/commit/96e97a5ce9b74de4d353f6d1720e3e134b40ea87

**Comment by skurvish** [comment]
@EricdeWaal can you retest this with alpha3 and determine if any of these issues still exist? Thanks.

**Comment by EricdeWaal** [comment]
There are still issues in Alpha3.
1. Ajaxified links from the list + Use Ajax upload: Yes > gives a 500 error "Fabrik has generated an incorrect query for the list "

2. Non-ajaxified links from the list + Use Ajax upload: Yes > gives an error 1064 "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE parent_id = administratie.id) AS `administratie___profielfoto`, (SELE...' at line 85 "

3. Non-ajaxified links from the list + Use Ajax upload: No > image cannot be deleted

4. Ajaxified links from the list + Use Ajax upload: No > image is not stored
 
5. no text string (EN) for PLG_ELEMENT_FILEUPLOAD_CONFIRM_SOFT_DELETE

**Comment by EricdeWaal** [comment]
And the above did not disappear in Beta1.

**Comment by EricdeWaal** [comment]
Edit: 3) it seems like the thumbnail is not re-created, when a new image is uploaded the old thumbnail is shown

**Comment by EricdeWaal** [comment]
And although the thumbnails in a list have an link <a ..... rel="lightbox[]" the imgage is not shown in a popup, just in a black page

**Comment by szotstihamer** [comment]
I can not figure out how to display uploaded images in a slideshow in a list. It only shows a loading gif.
