### ISSUE TITLE
Alpha2 - yes/no element rendered as editable in the detail view

### ISSUE THREAD

**Issue by lcollong** [joomlahenk/fabrik#400]
The yes/no element shows exactly the same way in the detail view that in the edit one. So you have the feeling you can change it.
I think in F3 it renders the same way as in the list view. Not very important but disturbing.

**Comment by skurvish** [comment]
Fixed in PR #407

**Comment by joomlahenk** [comment]
Fixed with updates in PR#419. Only issue left now is that only the goback button is on the details view. All buttons are on form edit and should not be on the details view (as in J!3). The goback button does not work however and need not be displayed.

**Comment by trob** [comment]
Go back button has always been on details view, too (and this makes sense to have it).
Opening a new issue for this.

**Comment by lcollong** [comment]
Alpha3 installed over an existing fresh alpha2 J4.2 (updated to 4.3 meanwhile) : Still showing as editable in details view.

**Comment by trob** [comment]
Confirmed.
It's ok if SEF is off.

**Comment by skurvish** [comment]
Hmmm, since my site never uses sef I always have it turned off. I can picture why it is not working and will get it fixed up shortly.

**Comment by trob** [comment]
I think the condition shouldn't be "details view" but "can edit" (there may be ACL restrictions also).

And as stated elsewhere: It seems to me that at some other point "can edit" is not checked correctly (it should call getReadOnlyOutput() directly) but I didn't find where.

**Comment by joomlahenk** [comment]
@lcollong : updated to 4.3 meanwhile ? We don't support J!4.3 yet, that's for april 2023. Maybe you mean J!4.2.3 ?

**Comment by lcollong** [comment]
Indeed. You're right. I've updated Joomla to 4.2.4. Running on a local wamp machine with PHP 8.1.0

**Comment by skurvish** [comment]
Should now be fixed with PR #454

**Comment by lcollong** [comment]
confirmed
